export const Logo = "https://help.nflxext.com/helpcenter/OneTrust/oneTrust_production_2025-07-24/consent/87b6a5c0-0104-4e96-a291-092c11350111/019808e2-d1e7-7c0f-ad43-c485b7d9a221/logos/dd6b162f-1a32-456a-9cfe-897231c7763c/4345ea78-053c-46d2-b11e-09adaef973dc/Netflix_Logo_PMS.png";
export const user_avtAR= "https://upload.wikimedia.org/wikipedia/commons/0/0b/Netflix-avatar.png";
export const API_OPTIONS={};
export const img_cdn="";
export const Moviejson = {
      results: [
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 123,
          original_language: "en",
          original_title:"Elemental",
          overview:"In the city where fire, water , land and air residents live together, a fiery young woman and a go with the flow guy.",
          popularity: 5517,
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
          release_date:"2023-06-14",
          title:"Elemental",
          video:false,
          vote_average:7.7,
          vote_count:1104
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 1234,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 1235,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 1236,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 1237,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 1238,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 1238,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 12310,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 12311,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 12312,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },

        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 12313,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 12314,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 12315,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 12316,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },
        {
          adult: false,
          backdrop_path: "/",
          genre_ids: [],
          id: 12317,
          original_language: "en",
          poster_path:"https://lumiere-a.akamaihd.net/v1/images/p_disneyplusoriginals_elemental_poster_rebrand_a0788af2.jpeg",
        },

      ],
    };